### ISSUE TITLE
Powershell Aliases

### ISSUE THREAD

**Issue by corysabol** [elreydetoda/vagrant-files#2]
Port some of the existing bash aliases and add some new alias to Powershell.
Also, supply an example Vagrantfile which uses envvars for parameterization.

For example something like the following should make it's way into the Powershell aliases.
```Powershell
<#
.SYNOPSIS
    .
.DESCRIPTION
    .
.PARAMETER VagrantFile 
    The path to the Vagrantfile to use .
.PARAMETER Name 
    Name of the resulting VM .
.PARAMETER DataDir
		Path of the directory to sync with the VM .
.PARAMETER Provision
		Whether or not to call vagrant up - ommission of this flag simply copies the Vagrantfile to the current dir .
.PARAMETER Gui
		Whether or not to start the VM with a GUI .
.EXAMPLE
		V-Init-Kali -Vagrantfile "C:\Vagrantfiles\kali\Vagrantfile" -Name "mykali" -DataDir ".\data" -Provision .
.NOTES
    Author: Cory Sabol 
#>
function V-Init-Kali {
  param (
    [String]$VagrantFile = 'C:\Vagrantfiles\kali\Vagrantfile',
    [String]$Name = 'kali',
    [String]$DataDir = '.\data',
    [switch]$Provision,
    [switch]$Gui
  )
  Copy-Item "$VagrantFile" -Destination . 
  if ($Provision) {
    // dirty hack
    $env:VMNAME=$Name
    $env:DATADIR=$DataDir
    if ($env) {
      $env:GUI=true
    } else {
      $env:GUI=false
    }
    vagrant up
  }
}
```
```Ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "kalilinux/rolling"
  config.vm.synced_folder ENV["DATADIR"], "/data"
  config.vm.provider "virtualbox" do |vb|
    vb.name = ENV["VMNAME"]
    # Display the VirtualBox GUI when booting the machine
    vb.gui = ENV["GUI"]
    # Customize the amount of memory on the VM:
    vb.memory = "4096"
  end
end
```

**Comment by corysabol** [comment]
@elreydetoda I'll make a PR as soon as I get some of your bash aliases ported to PS.

**Comment by elreydetoda** [comment]
cool :grin: since you are doing specifically kali for these commands I would recommend dropping it under this folder: https://github.com/elreydetoda/vagrant-files/tree/master/elrey741_kali-linux_amd64
also, I would recommend using the `elrey741/kali-linux_amd64` box instead of `kalilinux/rolling` because they (kalilinux) updated at a lot slower cadence than mine box (elrey741) that I build :grin: before this last week's update for 2020.2 they hadn't updated for 3 months...so at that pace you should just do normal kali install. I guess I am a little biased though :upside_down_face:

**Comment by elreydetoda** [comment]
So, @corysabol  #3 & #4 closes this one right?

**Comment by corysabol** [comment]
Yeah, they both close this one, but I only linked from #4
